//
//  TSNRESTObjectMap.m
//  todomvc
//
//  Created by Thomas Sunde Nielsen on 06.12.13.
//  Copyright (c) 2013 Thomas Sunde Nielsen. All rights reserved.
//

#import <objc/runtime.h>
#import "TSNRESTObjectMap.h"
#import "NSString+TSNRESTCasing.h"
#import "NSString+InflectorKit.h"
#import "NSString+TSNRESTContains.h"

@interface TSNRESTObjectMap ()

@end

@implementation TSNRESTObjectMap

+ (TSNRESTObjectMap *)autogeneratedMapForClass:(Class)classToInit {
    if (!classToInit)
        return nil;
    TSNRESTObjectMap *map = [[TSNRESTObjectMap alloc] initWithClass:classToInit];
    [map automapAllProperties];
    [map setAutomaticServerPath];
    return map;
}

- (id)initWithClass:(Class)classToInit
{
    self = [self init];
    if(self) {
        self.classToMap = classToInit;
        self.serverPath = [NSStringFromClass(classToInit) lowercaseString];
    }
    return(self);
}

- (id)init
{
    self = [super init];
    return self;
}

- (void)mapObjectKeys:(NSArray *)objectKeys toWebKeys:(NSArray *)webKeys
{
    for (int i = 0; i < objectKeys.count && i < webKeys.count; i++)
    {
        [self mapObjectKeys:[objectKeys objectAtIndex:i] toWebKeys:[webKeys objectAtIndex:i]];
    }
}

- (void)mapClass:(Class)classToMap toWebKey:(NSString *)webKey
{
    [self mapObjectKey:[NSStringFromClass(classToMap) decapitalizedString] toWebKey:webKey];
}

- (void)mapObjectKey:(NSString *)objectKey toWebKey:(NSString *)webKey
{
    NSMutableDictionary *dict = [NSMutableDictionary dictionaryWithDictionary:_objectToWeb];
    [dict setObject:webKey forKey:objectKey];
    self.objectToWeb = [NSDictionary dictionaryWithDictionary:dict];
}

- (void)mapObjectKey:(NSString *)objectKey toWebKeys:(NSArray *)webKey
{
    NSMutableDictionary *dict = [NSMutableDictionary dictionaryWithDictionary:_objectToWeb];
    [dict setObject:webKey forKey:objectKey];
    self.objectToWeb = [NSDictionary dictionaryWithDictionary:dict];
}

- (void)removeMappingForKey:(NSString *)objectKey {
    NSMutableDictionary *dict = [NSMutableDictionary dictionaryWithDictionary:_objectToWeb];
    [dict removeObjectForKey:objectKey];
    self.objectToWeb = [NSDictionary dictionaryWithDictionary:dict];
}

- (void)mapIdenticalKey:(NSString *)key
{
    [self mapObjectKey:key toWebKey:key];
}

- (void)mapIdenticalKeys:(NSArray *)keys
{
    for (NSString *key in keys)
        [self mapIdenticalKey:key];
}

- (void)mapCamelCasedObjectKeyToUnderscoreWebKey:(NSString *)key
{
    [self mapObjectKey:key toWebKey:[key stringByConvertingCamelCaseToUnderscore]];
}

- (void)mapCamelCasedObjectKeysToUnderscoreWebKeys:(NSArray *)keys
{
    for (NSString *key in keys)
        [self mapCamelCasedObjectKeyToUnderscoreWebKey:key];
}

-(void)addBoolean:(NSString *)boolean
{
    NSMutableDictionary *dict = [NSMutableDictionary dictionaryWithDictionary:self.booleans];
    [dict setObject:@YES forKey:boolean];
    self.booleans = [NSDictionary dictionaryWithDictionary:dict];
}

- (void)addBooleans:(NSArray *)booleans {
    for (NSString *boolean in booleans) {
        [self addBoolean:boolean];
    }
}

-(void)addEnumMap:(NSDictionary *)enumMap forKey:(NSString *)key
{
    NSMutableDictionary *dict = [NSMutableDictionary dictionaryWithDictionary:self.enumMaps];
    [dict setObject:enumMap forKey:key];
    self.enumMaps = [NSDictionary dictionaryWithDictionary:dict];
}

- (void)addClass:(Class)classType forKey:(NSString *)key {
    NSMutableDictionary *dict = [NSMutableDictionary dictionaryWithDictionary:self.keyClasses];
    [dict setObject:classType forKey:key];
    self.keyClasses = [NSDictionary dictionaryWithDictionary:dict];
    NSString *webKey = [[[key singularizedString] stringByConvertingCamelCaseToUnderscore] stringByAppendingString:@"_ids"];
#if DEBUG
    NSLog(@"Mapping %@ to %@ because of adding class %@", key, webKey, NSStringFromClass(classType));
#endif
    [self mapObjectKey:key toWebKey:webKey];
}

static const char *getPropertyType(objc_property_t property) {
    const char *attributes = property_getAttributes(property);
    char buffer[1 + strlen(attributes)];
    strcpy(buffer, attributes);
    char *state = buffer, *attribute;
    while ((attribute = strsep(&state, ",")) != NULL) {
        if (attribute[0] == 'T') {
            return (const char *)[[NSData dataWithBytes:(attribute + 3) length:strlen(attribute) - 4] bytes];
        }
    }
    return "@";
}

- (void)setAutomaticServerPath {
    self.serverPath = [[NSStringFromClass(self.classToMap) pluralizedString] lowercaseString];
}

- (void)automapAllProperties {
    unsigned int outCount, i;
    objc_property_t *properties = class_copyPropertyList(self.classToMap, &outCount);
    for (i = 0; i < outCount; i++) {
        objc_property_t property = properties[i];
        const char *propName = property_getName(property);
        if(propName) {
            const char *propType = getPropertyType(property);
            NSString *propertyName = [NSString stringWithCString:propName
                                                        encoding:[NSString defaultCStringEncoding]];
            NSString *propertyType = [NSString stringWithCString:propType
                                                        encoding:[NSString defaultCStringEncoding]];
            if ([propertyName isEqualToString:@"systemId"] || [propertyName isEqualToString:@"dirty"]) {
                continue;
            }
            else if ([propertyType containsString:@"NSString"] ||
                [propertyType containsString:@"NSNumber"] ||
                [propertyType containsString:@"NSDate"]) {
                [self mapCamelCasedObjectKeyToUnderscoreWebKey:propertyName];
            } else if ([NSClassFromString(propertyType) isSubclassOfClass:[NSManagedObject class]]) {
                NSString *webKey = [[NSString stringWithFormat:@"%@_id", [propertyName stringByConvertingCamelCaseToUnderscore]] decapitalizedString];
                [self mapObjectKey:propertyName toWebKey:webKey];
            }
        }
    }
}


- (void)logObjectMappings
{
    NSLog(@"Objectmappings for class %@ (server path: %@)", NSStringFromClass(self.class), self.serverPath);
    for (NSString *key in self.objectToWeb)
    {
        NSMutableString *logString = [NSMutableString stringWithFormat:@"Object: %@", key];
        for (long i = 15-key.length; i > 0; i--)
            [logString appendString:@" "];
        NSString *value = [self.objectToWeb objectForKey:key];
        [logString appendFormat:@"Web: %@", value];
        NSLog(@"%@", logString);
    }
}

@end
