//
//  DeserializerTests.m
//  Example
//
//  Created by Thomas Sunde Nielsen on 23.12.14.
//  Copyright (c) 2014 PAM. All rights reserved.
//

#import <XCTest/XCTest.h>
#import "NSArray+TSNRESTDeserializer.h"
#import "Brand.h"
#import "NSURLSessionDataTask+TSNRESTDataTask.h"

@interface DeserializerTests : XCTestCase

@end

@implementation DeserializerTests

- (void)setUp {
    [super setUp];
    [[TSNRESTManager sharedManager] addObjectMap:[TSNRESTObjectMap autogeneratedMapForClass:[Brand class]]];
    [(TSNRESTObjectMap *)[[TSNRESTManager sharedManager] objectMapForClass:[Brand class]] logObjectMappings];
}

- (void)tearDown {
    // Put teardown code here. This method is called after the invocation of each test method in the class.
    [super tearDown];
}

- (void)testThatDeserializerCanDeserializeJSON {
    NSURL *url = [[NSURL alloc] initFileURLWithPath:[[NSBundle mainBundle] pathForResource:@"Fixtures/JSON/brands" ofType:@"json"]];
    NSURLRequest *request = [NSURLRequest requestWithURL:url];
    
    XCTestExpectation *datataskExpectation = [self expectationWithDescription:@"Datatask complete"];
    
    NSURLSessionDataTask *task = [NSURLSessionDataTask dataTaskWithRequest:request success:^(NSData *data, NSURLResponse *response, NSError *error) {
        XCTAssert(data.length > 0, @"No valid data was provided from the fixtures.");
    } failure:^(NSData *data, NSURLResponse *response, NSError *error, NSInteger statusCode) {
        XCTFail(@"Data task failed.");
    } finally:^(NSData *data, NSURLResponse *response, NSError *error) {
        [datataskExpectation fulfill];
    } parseResult:YES];
    [task resume];
    
    
    [self waitForExpectationsWithTimeout:1 handler:^(NSError *error) {
        XCTAssert([Brand MR_countOfEntities] > 0, @"Got no brands in our db, parsing failed.");
    }];
}

//- (void)testPerformanceExample {
//    // This is an example of a performance test case.
//    [self measureBlock:^{
//        // Put the code you want to measure the time of here.
//    }];
//}

@end
