//
//  MapTests.m
//  Example
//
//  Created by Thomas Sunde Nielsen on 22.12.14.
//  Copyright (c) 2014 PAM. All rights reserved.
//

#import <XCTest/XCTest.h>
#import "TSNRESTObjectMap.h"
#import "Product.h"

@interface MapTests : XCTestCase

@property (nonatomic, strong) TSNRESTObjectMap *referenceMap;

@end

@implementation MapTests

- (void)setUp {
    [super setUp];
    
    /*
     Assuming current test model looks like this. If new export from Core Data has been run, please update this setUp method.
     @property (nonatomic, retain) NSNumber * systemId;
     @property (nonatomic, retain) NSString * name;
     @property (nonatomic, retain) NSString * descr;
     @property (nonatomic, retain) NSNumber * inventory;
     @property (nonatomic, retain) NSNumber * priceGross;
     @property (nonatomic, retain) NSNumber * visible;
     @property (nonatomic, retain) NSDate * createdAt;
     @property (nonatomic, retain) Shop *shop;
     @property (nonatomic, retain) Brand *brand;
     */
    
    self.referenceMap = [[TSNRESTObjectMap alloc] initWithClass:[Product class]];
    // systemId is a special case. See https://github.com/PAM-AS/TSNREST/issues/33
    [self.referenceMap mapObjectKey:@"name" toWebKey:@"name"];
    [self.referenceMap mapObjectKey:@"descr" toWebKey:@"descr"];
    [self.referenceMap mapObjectKey:@"inventory" toWebKey:@"inventory"];
    [self.referenceMap mapObjectKey:@"priceGross" toWebKey:@"price_gross"];
    [self.referenceMap mapObjectKey:@"visible" toWebKey:@"visible"];
    [self.referenceMap mapObjectKey:@"createdAt" toWebKey:@"created_at"];
    [self.referenceMap mapObjectKey:@"shop" toWebKey:@"shop_id"];
    [self.referenceMap mapObjectKey:@"brand" toWebKey:@"brand_id"];
}

- (void)tearDown {
    // Put teardown code here. This method is called after the invocation of each test method in the class.
    [super tearDown];
}

- (void)testThatAutomappingCreatesCorrectNumberOfMappings {
    TSNRESTObjectMap *comparisonMap = [TSNRESTObjectMap autogeneratedMapForClass:[Product class]];
    XCTAssert(self.referenceMap.objectToWeb.count == comparisonMap.objectToWeb.count, @"Automapping didn't map the correct number of objects (should be %li, is %li)", self.referenceMap.objectToWeb.count, comparisonMap.objectToWeb.count);
}

- (void)testThatAutomappingGeneratesCorrectWebKeys {
    TSNRESTObjectMap *comparisonMap = [TSNRESTObjectMap autogeneratedMapForClass:[Product class]];
    for (NSString *key in comparisonMap.objectToWeb) {
        NSString *referenceWebKey = [self.referenceMap.objectToWeb objectForKey:key];
        NSString *comparisonWebKey = [comparisonMap.objectToWeb objectForKey:key];
        XCTAssertEqualObjects(referenceWebKey, comparisonWebKey, @"Autogenerated web key (%@) doesn't match reference (%@)", comparisonWebKey, referenceWebKey);
    }
}


@end
