//
//  URLRequestTests.m
//  Example
//
//  Created by Thomas Sunde Nielsen on 03.02.15.
//  Copyright (c) 2015 PAM. All rights reserved.
//

#import <UIKit/UIKit.h>
#import <XCTest/XCTest.h>
#import "TSNRESTManager.h"
#import "NSURLRequest+TSNRESTConveniences.h"
#import "Product.h"

@interface URLRequestTests : XCTestCase

@end

@implementation URLRequestTests

- (void)setUp {
    [super setUp];
    
    TSNRESTManager.sharedManager.configuration.baseURL = [NSURL URLWithString:@"http://example.com/api/v1/"];
    [TSNRESTManager.sharedManager addObjectMap:[TSNRESTObjectMap autogeneratedMapForClass:[Product class]]];
}

- (void)tearDown {
    // Put teardown code here. This method is called after the invocation of each test method in the class.
    [super tearDown];
}

- (void)testThatURLRequestWithQueryFormatCorrectly {
    NSString *query = @"?include=awesomeness&limit=10";
    
    NSURLRequest *request = [NSURLRequest requestForClass:[Product class] query:query];
    
    XCTAssertEqualObjects(request.URL.absoluteString, [@"http://example.com/api/v1/products?include=awesomeness&limit=10" stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding], @"URLs aren't equal");
}

- (void)testThatURLRequestWithIdsFormatCorrectly {
    NSArray *ids = @[@1, @2, @3, @4, @6, @10];
    
    NSURLRequest *request = [NSURLRequest requestForClass:[Product class] ids:ids];
    
    XCTAssertEqualObjects(request.URL.absoluteString, [@"http://example.com/api/v1/products?ids[]=1&ids[]=2&ids[]=3&ids[]=4&ids[]=6&ids[]=10" stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding], @"URLs aren't equal.");
}

- (void)testThatURLRequestGetsCorrectHeaders {
    NSDictionary *headers = @{@"X-TSNREST-TESTING":@"true",@"X-TSNREST-HEADER":@"not-so-secret"};
    for (NSString *key in headers) {
        [TSNRESTManager.sharedManager setGlobalHeader:headers[key] forKey:key];
    }
    
    NSURLRequest *request = [NSURLRequest authenticatedRequest];
    NSLog(@"Headers: %@", request.allHTTPHeaderFields);
    
    // Add +1 for the content header that gets set by authenticatedRequest
    XCTAssert(request.allHTTPHeaderFields.count == headers.count+1, @"Wrong number of headers set. Expected %tu, got %tu", headers.count, request.allHTTPHeaderFields.count);
    for (NSString *key in request.allHTTPHeaderFields) {
        if ([key isEqualToString:@"Content-Type"]) {
            XCTAssert([request.allHTTPHeaderFields[key] isEqualToString:@"application/json"]);
        } else {
            XCTAssertEqualObjects(request.allHTTPHeaderFields[key], headers[key], @"Header values not equal. Expected %@, got %@", headers[key], request.allHTTPHeaderFields[key]);
        }
    }
}

@end
